from typing import NamedTuple

Question = NamedTuple("Question", [("desc", str), ("answers", list[str]), ("score", list[int])])

QUIZ : list[Question] = [
    Question("Before the quiz begin, choose:", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
    Question("", [""], [0]),
]